### ISSUE TITLE
Bug on publishing data for devices.

### ISSUE THREAD

**Issue by emmanuelbertho** [SeppPenner/SparkplugNet#28]
Hello,

In the method PublishMessageForDevice in SparkplugNode.cs you are generating the payload with the known metrics of the node instead of the known metrics of the device.
That means if you don't register the metrics in both the node and the device you can't publish data for a device.

I replaced `this.KnownMetricsStorage.FilterOutgoingMetrics(metrics)` with `deviceMetrics` in the method and it is working well.

**Comment by SeppPenner** [comment]
Yeah, that sounds like a bug to me. I will check it soon :)

**Comment by SeppPenner** [comment]
It seems that we need two different metrics stores here.

**Comment by SeppPenner** [comment]
Ah, I see. I guess, `this.KnownMetricsStorage.FilterOutgoingMetrics(deviceMetrics)` should fix the issue, correct?

**Comment by emmanuelbertho** [comment]
> 

I don't think that node a should be aware of the metrics of all his devices. Well I didn't saw anything that says so in the Sparkplug B documentation. Correct me if I am wrong

**Comment by Patrick2607** [comment]
> > 
> 
> I don't think that node a should be aware of the metrics of all his devices. Well I didn't saw anything that says so in the Sparkplug B documentation. Correct me if I am wrong

You might be right, I haven't found that either when I just checked, it was my understanding. However, the proposed solution in the commit is not what you intended right? In your OP you said to replace that whole line with `deviceMetrics`, but in the commit, only the parameter has been replaced like this: `this.KnownMetricsStorage.FilterOutgoingMetrics(deviceMetrics)`. This causes the issue I mentioned above. Doing it your way works, but it does not catch unknown Metrics.

I think each Device needs its own MetricStorage. Agreed?

**Comment by SeppPenner** [comment]
I guess this was my mistake, the devices should have an own metrics storage for sure...

**Comment by Patrick2607** [comment]
> I guess this was my mistake, the devices should have an own metrics storage for sure...

I'm working on it right now :) seems like a fairly easy fix

**Comment by SeppPenner** [comment]
I've seen it, I hope to check and test it today :)

**Comment by SeppPenner** [comment]
New version available soon :)
