### ISSUE TITLE
"How to use" Example Fails with No Feedback

### ISSUE THREAD

**Issue by jlschrag** [SeppPenner/SparkplugNet#34]
I have been trying to get the Sparkplug B portion of the "how to use" code working without success.  I have a project targeting .NET Framework 4.7.2.  The code was copy/pasted from the "how to use" page, with a couple fixes for callback functions that appear to have been renamed.

When I run, it makes it to `node.Start()`, then just exits.  No logging via Serilog, nothing to the console, nothing to the debug output window in VS.

I dropped the SparkplugNet NuGet package, and added the source directly to allow debugging.   `Start()` calls `ConnectInternal()` calls `this.Client.ConnectAsync()`.  That last call is part of MQTTNet, which is another black box.  I tried adding MQTTNet source directly, but that is a can of worms.

**Am I missing some easy way of getting feedback on what is going wrong?**  I did add SeriLog packages for console & file sinks, and this code before calling `node.Start()`:
```
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Console()
                .WriteTo.File("logs/JoesLog.txt", rollingInterval: RollingInterval.Day)
                .MinimumLevel.Verbose()
                .CreateLogger();
```

I can log something myself and see it in both console & file, but neither SparkplugNet nor MQTTNet log anything.

_Update: MQTTNet appears to be using .NET 4.6.1 code, which results in a crash.  Detailed [here](https://stackoverflow.com/questions/74734523/why-does-nuget-package-reference-incorrect-net-framework-standard)._

**Comment by SeppPenner** [comment]
Strange behaviour. I had something similar with a Serilog sink I provide on my own, but the issue is still unresolved as well... I'll test this soon and see if I find a solution. Sounds like dll hell once more :/

**Comment by SeppPenner** [comment]
This is not relevant anymore since the library only supports Net6, 7 and 8 at the moment...
