### ISSUE TITLE
Question: QoS

### ISSUE THREAD

**Issue by michael-benoit** [SeppPenner/SparkplugNet#38]
How do I specify the QoS of a message to publish?

**Comment by SeppPenner** [comment]
Good question, I need to check this again. Still some time after my last changes here...

**Comment by SeppPenner** [comment]
The short answer at the moment is: You can't :D Don't ask me why, but somehow I assumed that all Sparkplug messages should be sent with QoS=1 (Which in 2.2 was only the case for state messages as far as I researched it now). I will try to change this and provide full 3.0 compatibility with the TCK from Ecplise as requested under https://github.com/SeppPenner/SparkplugNet/issues/39, so I guess you need to wait for that to be done.

**Comment by SeppPenner** [comment]
Needs to be checked. Some messages must be sent with QoS 0 and retain = false (E.g. NBIRTH, NDATA).

**Comment by SeppPenner** [comment]
Is checked against Sparkplug version 3.0:

NBIRTH --> QoS = 0
NDEATH --> Not fix
DBIRTH --> QoS = 0
DDEATH --> QoS = 0
NDATA --> QoS = 0
DDATA --> QoS = 0
NCMD --> QoS = 0
DCMD --> QoS = 0
STATE --> QoS = 1

Only NDEATH allows to specify a QoS explicitely.

**Comment by SeppPenner** [comment]
Updated: Completely invalid:

* Edge node will message QoS must be set to `1`.
* Edge node will message retain flag must be set to `false`.
