### ISSUE TITLE
Datetime metric types

### ISSUE THREAD

**Issue by evonz-mx** [SeppPenner/SparkplugNet#55]
Hi folks,

When writing a DateTime value, the sparkplug data type is converted to Int64 (4).  But I'm hoping to keep the datatype as DateTime (13).  I think this is happening because ValueBaseVersionB.SetValue sets the value via .LongValue, but doesn't preserve the type.

Is this intended?  Should I be overriding the metric's type after instantiation (as I am currently doing to work around this issue)?

**Comment by SeppPenner** [comment]
Will be done, for my reference https://github.com/eclipse/tahu/blob/5736e404889d4b95910613040a99ba79589ffb13/java/lib/core/src/main/java/org/eclipse/tahu/message/SparkplugBPayloadDecoder.java and https://github.com/eclipse/tahu/blob/5736e404889d4b95910613040a99ba79589ffb13/java/lib/core/src/main/java/org/eclipse/tahu/message/SparkplugBPayloadEncoder.java.

**Comment by SeppPenner** [comment]
Should be fixed after https://github.com/SeppPenner/SparkplugNet/commit/4fdb44934b65764d2d589e7ac5b4fab9b7474a93 (Version 1.3.0+).

**Comment by evonz-mx** [comment]
Thanks very much!  I look forward to trying this fix out in our application.

**Comment by SeppPenner** [comment]
I'm not yet sure if this works properly already. I still need to iplement more serialization Tests here...
