### ISSUE TITLE
SparkplugApplication Required Known Metrics

### ISSUE THREAD

**Issue by ankitagojiya** [SeppPenner/SparkplugNet#58]
1. According to sparkplug specificaton there is no need for host application to know what kind of metrics can be received from edge node . 

But according to SparkplugNet package implementation predefined NBIRTH/Metrics in the constructor must be given to start the host application. Ideally, Host application should be started without know metrics.

**Line 26 : [SparkplugNet/src/SparkplugNet/VersionB/SparkplugApplication.cs at master · SeppPenner/SparkplugNet · GitHub](https://github.com/SeppPenner/SparkplugNet/blob/master/src/SparkplugNet/VersionB/SparkplugApplication.cs)**

![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/d9ac7170-ae8d-438a-8284-68b49718e83b)

2.The package internally validates incoming NBIRTH metrics with metrics saved in KnownMetricsStorage and does not fire the NodeBirthReceived and NodeDataReceived event if we give an empty metrics list(as per point 1) to start the host application and later when the edge node publishes NBIRTH. 

![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/e1ffbe51-7dd6-4bca-bf78-de35ae2d5e4a)

![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/40f7bf5f-524a-4011-922f-c6bbbf5aa2d4)

**Line 147 : [SparkplugNet/src/SparkplugNet/VersionB/SparkplugApplication.cs at master · SeppPenner/SparkplugNet · GitHub](https://github.com/SeppPenner/SparkplugNet/blob/master/src/SparkplugNet/VersionB/SparkplugApplication.cs)**

**Comment by SeppPenner** [comment]
I guess, you're right here. Need to check it though...

**Comment by ankitagojiya** [comment]
@SeppPenner 
Any updates on this ?

**Comment by buentead** [comment]
@SeppPenner : I'm also interested in this fix. Do you have any timeframe when this will be fixed? Thanks.

**Comment by mikolajwalus** [comment]
Same here, we would like to use this for our projekt to work as primary host scada but for work application needs to know all the metrics from the start which is a no go. This fix also looks reasonable  https://github.com/SeppPenner/SparkplugNet/pull/50/files#diff-b1c3e69c5f877405f006317b3e1cc8a2c89e9d89cb94979c339d4edf9ab28739

**Comment by SeppPenner** [comment]
I'm honestly not yet sure what is correct here, but I will remove this for now.

My main problem is that I didn't have the time to check again on V3 (And that the last time I checked, the Testkit from Eclipse didn't want to start properly as yarn had issues)...

**Comment by SeppPenner** [comment]
Version 1.3.1 is coming soon where this is removed (I still want to review this once I'm able to...)
