### ISSUE TITLE
Implementing as Primary Application

### ISSUE THREAD

**Issue by MRIIOT** [SeppPenner/SparkplugNet#6]
What is known to be missing in order to build a SpB Primary Application on top of the library?

**Comment by SeppPenner** [comment]
Well, I hope nothing to be honest :D

**Comment by SeppPenner** [comment]
> Something I noticed is that the metrics have to been known ahead of time by the application. Sending new metrics from nodes, ends up in here:
> 
> https://github.com/SeppPenner/SparkplugNet/blob/ed77d8aec6489af663f9578b2e3516b82dfff293/src/SparkplugNet/Core/Application/SparkplugApplicationBase.cs#L568

I assumed that this was intended within Sparkplug...

**Comment by MRIIOT** [comment]
It's probably implementation specific, but I would expect arbitrary nodes and devices to connect to the primary application without any previous knowledge.

**Comment by SeppPenner** [comment]
Sorry for the late reply. I will check this within the next days and provide an update.

**Comment by SeppPenner** [comment]
I will close this now, since I believe this is according to the standard. If anyone has more information or clearification, just contact me here, please :)

**Comment by MRIIOT** [comment]
> I will close this now, since I believe this is according to the standard. If anyone has more information or clearification, just contact me here, please :)

That's fine.  Once I have more time, I will re-open this with examples.
