### ISSUE TITLE
ArrayValues are missing metrics

### ISSUE THREAD

**Issue by ankitagojiya** [SeppPenner/SparkplugNet#64]
Hello @SeppPenner 

As per issue [https://github.com/SeppPenner/SparkplugNet/issues/54](https://github.com/SeppPenner/SparkplugNet/issues/54)  , I think you have added the array datatypes but its related values are still missing in metrics , pls refer below image which don't have any **_StringArrayValue_** or any array values

![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/1af8cc2b-8f23-4bfc-b17c-3de4202a0b79)

**Comment by SeppPenner** [comment]
This is mainly the same issue as https://github.com/SeppPenner/SparkplugNet/issues/63, I guess.

**Comment by SeppPenner** [comment]
Update is planned for tomorrow.

**Comment by SeppPenner** [comment]
Version 1.3.2 is out soon and should fix this.

**Comment by ankitagojiya** [comment]
Hello @SeppPenner , That's not available in version 1.3.2.

I mean if you are giving support of string array than I am able to set the value of string array.

For e.g. If I select string data type then I will add value in StringValue property. Same way If I select datatype as StringArray on which property I have to filed that value?

Example of string array value : ["Test1","Test2"]

**Comment by shouidar** [comment]
Looks like all the Array data types are not implemented yet. @SeppPenner please confirm.

**Comment by ankitagojiya** [comment]
Yes , Also please can you reopen the issue if it's not implemented yet.

**Comment by SeppPenner** [comment]
I guess, you're right. I am currently testing with a broad unit test to find all issues with serialization here... Might take some time though. I hope to provide a solution until Saturday...

**Comment by ankitagojiya** [comment]
Appreciate it , Thank you

**Comment by SeppPenner** [comment]
I'm nearly done now. Some tests still fail because of issues with signed / unsigned values.

**Comment by malavvvakharia** [comment]
@SeppPenner, do you have a specific time for releasing this issue? I'm blocked by a bug.

**Comment by SeppPenner** [comment]
Fixed with https://github.com/SeppPenner/SparkplugNet/releases/tag/1.3.3.
