### ISSUE TITLE
Metric Values sent with default values instead of preassigned values.

### ISSUE THREAD

**Issue by shouidar** [SeppPenner/SparkplugNet#65]
All Metrics sent with NDATA, DDATA, NBIRTH, DBIRTH sent with values set to default (0 for float and false for boolean) as reported by Mqtt.Fx.

Looks like there is an issue with protobuf.

![Screenshot 2024-02-03 002549](https://github.com/SeppPenner/SparkplugNet/assets/10144958/9cad1a3a-615c-4978-8526-8049da6e7df7)

### To reproduce:
Cloned the project in Visual Studio 2022 and run the example application. Monitored  pubished message with Mqtt.Fx.

**Comment by shouidar** [comment]
I think the problem is in ConvertVersionBMetric, assigning several datatypes during the Metric object creation will cause the internal Discriminated union to default to the last assignment independently of the Datatype property. 
See Watch values in the screenshot below.
![Metric_Assignement](https://github.com/SeppPenner/SparkplugNet/assets/10144958/24e1559e-cc0d-4156-88c3-be4cf86ee150)

**Comment by shouidar** [comment]
Just noticed this is beeing addressed in issue #63.
Closing this topic.

**Comment by SeppPenner** [comment]
> Just noticed this is beeing addressed in issue #63. Closing this topic.

Thank you, yes, this is the same issue.
