### ISSUE TITLE
Not able to publish metrics with values from edge node (For all datatypes)

### ISSUE THREAD

**Issue by ankitagojiya** [SeppPenner/SparkplugNet#66]
Hello @SeppPenner ,

Facing issue while publishing metrics with any kind of values (like.. Int , string , dataset) , at the time of converting payload into VersionBPayload (Image 1) it is overriding all the values (Image 2) that's why only the last datatype which is template (image 2) is working in version 1.3.1 , maybe we have to break the process after assigning values to any type of metric datatype which was working fine in version 1.2.0 (Image 3)

Please refer to all images below

Image 1
![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/bc76febd-0210-4f7b-afdb-41e2b7aa3327)

Image 2
![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/8a57ec3d-54d8-4da9-8b5c-ec4b16e231fb)

![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/a028b24d-9cb1-4762-820a-a80560a6790a)

Image 3 (According to version 1.2.0)
![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/82a1c769-5793-458d-b56d-71af32bcad1a)
![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/0f33255f-74b0-43b3-a5b1-75c8a6097ce4)

**Comment by shouidar** [comment]
see issue #63

**Comment by SeppPenner** [comment]
This is mainly the same issue as https://github.com/SeppPenner/SparkplugNet/issues/63, I guess.

**Comment by SeppPenner** [comment]
Version 1.3.2 is out soon and should fix this.
