### ISSUE TITLE
Sparkplug version B not working

### ISSUE THREAD

**Issue by omarkamel02** [SeppPenner/SparkplugNet#7]
I have tried to use the package for version A testing, using the given examples i created a node and an application that listens on the metrics and things went so good

But when i tried with almost the same scenario with the given examples for version B, the metrics from the node are queued at the Broker for the application and never reach the application side

**Comment by omarkamel02** [comment]
I investigated in the issue and found a solution that made things work smoothly but I'm not sure weather it is right or wrong regarding the sparkplug specification or the way the package is running,

in payloadconverter.cs in ConvertVersionBMetric() method, the metric.DatasetValue parameter is always null  so ConvertVersionBDataSet() method in this case has an exception because of the null argument

the solution is before calling the ConvertVersionBDataSet() method, I check first if the metric.DatasetValue is not null and if it is null we assign null to the converted metric dataset value with null also and we don't call ConvertVersionBDataSet() method

this solution also was made with other Metric data values.

**Comment by SeppPenner** [comment]
Er, ok. Sounds strange to me somehow :D I need to check it.

**Comment by SeppPenner** [comment]
> the solution is before calling the ConvertVersionBDataSet() method, I check first if the metric.DatasetValue is not null and if it is null we assign null to the converted metric dataset value with null also and we don't call ConvertVersionBDataSet() method

> this solution also was made with other Metric data values.

So, the solution I can provide is to check all metric values for null and only add them if not null?

**Comment by SeppPenner** [comment]
I hope that this is now fixed in version 0.6 (Will be out soon). If not, just re-open the issue.
