### ISSUE TITLE
NCMD Event only receive single metric

### ISSUE THREAD

**Issue by adityashahazilen** [SeppPenner/SparkplugNet#73]
As per Sparkplug specification "Multiple metrics can be supplied in a single NCMD message". This means when Host Application publish NCMD with multiple metrics then Edge Node should receive all metrics in the single event. At the moment, NodeCommandReceived event only receive single metrics as a argument.

**Existing Code**
![image](https://github.com/SeppPenner/SparkplugNet/assets/132545158/71fd2848-3c1a-4f70-b916-0abeecdca321)

It should be like below to handle multiple metrics
![image](https://github.com/SeppPenner/SparkplugNet/assets/132545158/42e5337d-45a4-4a5b-a2ad-6351fb5970b7)

**Comment by shouidar** [comment]
The _SparkPlugNode_ rises an event for each Metric received in the NCMD message:
```c#
case SparkplugMessageType.NodeCommand:
                    foreach (var metric in convertedPayloadVersionB.Metrics)
                    {
                        if (metric is VersionBData.Metric convertedMetric)
                        {
                            await this.FireNodeCommandReceivedAsync(convertedMetric);
                        }
                    }

                    break;
```
But I do prefer the idea of a single event with all the metrics.

**Comment by SeppPenner** [comment]
I guess, we can do that. Seems legit.
