### ISSUE TITLE
Remove dependency of Serilog

### ISSUE THREAD

**Issue by tkouba** [SeppPenner/SparkplugNet#74]
Please remove dependency of Serilog.

**Comment by SeppPenner** [comment]
Why should I?  It's honestly the best logging framework I have worked with until now...

**Comment by tkouba** [comment]
Because there are a lot of logging frameworks. Dependency of any logging framework from general use library is not a good idea. This dependency may violate some rules for application and library cannot be used.

**Comment by shouidar** [comment]
Although I agree that depending on SeriLog is overkill, I think the library should allow for some optional logging mechanism. This can be achieved easily by depending only on the _Microsoft.Extensions.Logging.Abstractions_ and optionally the default ILogger or any compatible logging framework (including SeriLog if desired) or null if logging is not required. The library would prefix all local ILogger calls with the null check operator to handle the null logger case. 
See "[Loggin in a .Net Core library](https://xfischer.github.io/logging-dotnet-core/)" for more details.

**Comment by SeppPenner** [comment]
The question is if we really need it. There was only debugging logs in the code. I mean, I can add it if desired.

**Comment by malavvvakharia** [comment]
@SeppPenner , On the NuGet side 1.3.4 is not available. So do 1.3.3 and 1.3.4 have the same code?

![image](https://github.com/SeppPenner/SparkplugNet/assets/160019245/0874c05c-2dba-4960-9540-c0b61e603310)

**Comment by SeppPenner** [comment]
@malavvvakharia I guess, I forgot to push it. Should be there soon 😅
