### ISSUE TITLE
Not able to access StringValue, IntValue, TemplateValue but all the details will be now come under the value section.(Version 1.3.4)

### ISSUE THREAD

**Issue by malavvvakharia** [SeppPenner/SparkplugNet#86]
Hello @SeppPenner ,

Is there any enhancement or specific reason for not giving the data in IntValue, StringValue, or any other type? (It is properly working before the version release of 1.3.4)

![image](https://github.com/SeppPenner/SparkplugNet/assets/160019245/94dbc74d-0e9d-433a-ab0b-e177e9657fb4)

According to the below SS is not able to access the StringValue,IntValue, etc.:

![image](https://github.com/SeppPenner/SparkplugNet/assets/160019245/4215191d-4314-4e50-92f9-f408d783815e)

**Comment by SeppPenner** [comment]
Basically, the internal metrics have changed in version 1.3.4 which means that there is only `Value` that is filled according to the data type specified. So, if you input / receive a metric with type `String`, the value will be a `string` value, but its generic type is `object` for convenience issues / simplification.

You can try `metricValue.Value as string stringValue` or something like

```csharp
if (metricValue.Value is string stringValue)
{
    // Do something with the string value from 'stringValue'
}
```

This is not a bug, but intended behaviour as I wanted to have a generic API that works with all data types equally.

**Comment by malavvvakharia** [comment]
Thanks for the information @SeppPenner .
I am confused as it is not mentioned in the release version of 1.3.3 and 1.3.4.
(https://github.com/SeppPenner/SparkplugNet/releases/tag/1.3.4)
