### ISSUE TITLE
birth metrics not passed to FireNodeBirthRecevied

### ISSUE THREAD

**Issue by jeff-pf** [SeppPenner/SparkplugNet#92]
Using the sample example application - OnApplicationVersionBNodeBirthReceived is not receiving the birth metrics. 

Looking at ShouldVersionBMetricBeAdded - shouldbeAdded is always false since the metrics are not in KnownMetrics

                // Name only is set.

                // Check if the metric is known.
                if (!this.knownMetricsByName.TryGetValue(metric.Name, out var foundMetric))
                {
                    shouldbeAdded = false;
                    this.Logger?.LogError("The metric {Metric} is removed because it is unknown.", metric);
                }

Am I missing something?  There would not be any know metrics until added from a birth message.

**Comment by SeppPenner** [comment]
>There would not be any know metrics until added from a birth message.

Yes, and this is desired.

All metrics must be known in advance, e.g. 

```csharp
private static readonly List<VersionBData.Metric> VersionBMetricsApplication =
[
    new VersionBData.Metric("temperatureApplication", VersionBData.DataType.Float, 1.20f),
    new VersionBData.Metric("climateactiveApplication", VersionBData.DataType.Boolean, true)
    {
        Properties = new VersionBData.PropertySet
        {
            Keys = ["ON", "OFF"],
            Values =
            [
                new(VersionBData.DataType.Int8, 1)
                {
                },
                new(VersionBData.DataType.Int8, 0)
                {
                }
            ]
        }
    }
];

var application = new VersionB.SparkplugApplication(VersionBMetricsApplication, SparkplugSpecificationVersion.Version22);
```

Afterwards, you can `Start` the node / application to run or `Stop` it. The rest should be done automatically. I have changed the order of the examples however (Register event handlers before anything else happens), maybe that was also an issue (See https://github.com/SeppPenner/SparkplugNet/commit/8b72a43f283ae20d9a3b83f6de83ce194a679b0e)...

For more information, you can check https://github.com/SeppPenner/SparkplugNet/issues/85 as well, where we discussed this.

Concluding:
- Metrics must be known in advance.
- If an unknown metric is received, it will be dropped (I agree, that this might change in the future as in the specs this would mean to send a `Node Rebirth` command as well though).
- I will try to add https://github.com/SeppPenner/SparkplugNet/issues/44 as soon as possible to do a custom node rebirth which would result in new known metrics as well.
